all:
	g++ -std=c++11 -Wall -g client.cpp Connection.cpp Socket.cpp SocketException.cpp Message.cpp Ip.cpp -o client
	g++ -std=c++11 -Wall -g server.cpp Connection.cpp Socket.cpp SocketException.cpp Message.cpp Ip.cpp -o server
